dist: xenial
language: python
python: 3.7
cache: pip
install:
  - pip install -r requirements.pip -c requirements.txt
  # Lint requirements.
  - pip install therapist black flake8
script:
  - therapist run --use-tracked-files *.py
